# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_generator.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15image_generator.proto\x12\x05image\"\x1e\n\x0cImageRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"\"\n\rImageResponse\x12\x11\n\timage_url\x18\x01 \x01(\t2L\n\x0eImageGenerator\x12:\n\x0bGetImageUrl\x12\x13.image.ImageRequest\x1a\x14.image.ImageResponse\"\x00\x42\tZ\x07./imageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_generator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./image'
  _globals['_IMAGEREQUEST']._serialized_start=32
  _globals['_IMAGEREQUEST']._serialized_end=62
  _globals['_IMAGERESPONSE']._serialized_start=64
  _globals['_IMAGERESPONSE']._serialized_end=98
  _globals['_IMAGEGENERATOR']._serialized_start=100
  _globals['_IMAGEGENERATOR']._serialized_end=176
# @@protoc_insertion_point(module_scope)
